version: "3.3"
services:
  footer-service:
    container_name: emp-footer
    image: ipreencekmr/emp-footer
    restart: on-failure
    ports:
      - 3005:3000

  container-service:
    container_name: emp-container
    image: ipreencekmr/emp-container
    restart: on-failure
    depends_on:
      - home-service
    ports:
      - 3002:3002

  home-service:
    container_name: emp-home
    image: ipreencekmr/emp-home
    restart: on-failure
    depends_on:
      - employee-service
      - address-service
    ports:
      - 3003:3003

  employee-service:
    container_name: emp-employee
    image: ipreencekmr/emp-employee
    restart: on-failure
    ports:
      - 3006:3000

  address-service:
    container_name: emp-address
    image: ipreencekmr/emp-address
    restart: on-failure
    ports:
      - 3007:3000