name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm install
    
    - name: Build Production
      run: npm run build
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ipreencekmr/emp-root
      
    - name: Docker Login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Publish Image
      run: docker push ipreencekmr/emp-root
